### ISSUE TITLE
Support non-unique indexes

### ISSUE THREAD

**Issue by lun3x** [lun3x/multi_index_map#1]
Often we want to store and retrieve all elements with a field matching a certain value, ie. the index is non-unique.

**Comment by lun3x** [comment]
https://github.com/lun3x/multi_index_map/tree/non_unique_indexes

**Comment by lun3x** [comment]
Retrieval semantics are still a WIP. We cannot simply provide a slice of values matching the given key, as they may not stored in contiguous memory for a given index. In c++ this is handled by providing a pair of iterators `[start, end)` but this can lead to multiple aliasing, so not workable in rust. Returning a Vec of references is a potential option. However, the Vec has to be constructed on-the-fly so maybe not ideal due to memory allocation. Perhaps some form of special iterator that yields matching values until there are no more to match? This can then be `collect()`ed into a Vec as required.

**Comment by GamePad64** [comment]
Wow, I did a search about a month ago, looking for boost::multiindex alternative in Rust. And now it is here! Great work!
Looking forward for a non-unique index to use this library as a generic in-memory storage for table data.

**Comment by lun3x** [comment]
Thanks! Non-unique indexes are now available. We provide both an Iterator `.iter_by_field()` and retrieval `.get_by_field()` , `remove_by_field()` methods. Currently `.modify_by_field()` and `.get_mut_by_field()`  are not supported. When iterating between different values in the index we will yield in the order defined by the container (BTreeMap/FxHashMap). 
 When iterating over a specific value in an index with multiple matching elements, we yield them in the order they were inserted. When retrieving all elements for a given index we provide a Vec of references to elements in the backing storage. This requires allocation, however this can be avoided through the use of the `.iter_by_field()` methods.

Further work needs to be done to support `.modify_by_field()` to enable modification of all elements matching a specific non-unique index value.

**Comment by lun3x** [comment]
Okay I think by merging the PR from @wyjin this issue can now be closed!
