### ISSUE TITLE
[Feature Request] Soft handle the error when try to insert a data with same unique-key.

### ISSUE THREAD

**Issue by RuofengX** [lun3x/multi_index_map#45]
A panic would raise when trying to insert a data with unique-key (already in the map), which is annoying.  
How about implement a method `try_insert` that return a Result<(), Error>, but not raising panic?

- Panic is much hard to recovery than a Result.
- Many function in standard library have a "try-to" version

I am looking into the source code,  the insert method would [panic here](https://github.com/lun3x/multi_index_map/blob/da13ec3f422f93843ba6ac7db18a0c7249580249/multi_index_map_derive/src/generators.rs#L215) when a value from raw index is detected, which means there is an entry already.

**Comment by lun3x** [comment]
The issue with this is that we may have successfully inserted some of the other indexed fields already. Then we would need to "roll back" these inserts, or the table is in a invalid state.
The other solution would be to go through and check all indexed fields can be inserted, then go through them all again to perform the insert. This is fairly complex, although potentially doable with minimal overhead with the entry API.

**Comment by lun3x** [comment]
Actually not too complicated, I've implemented this feature in a way that should have no overhead.
