### ISSUE TITLE
Embedded indexes

### ISSUE THREAD

**Issue by OvermindDL1** [lun3x/multi_index_map#48]
Say I have a mock-up like this:

```rs
struct Inner {
  blah: String,
  more: String
}

#[derive(MultiIndexMap)]
struct Outer {
  #[multi_index(hashed_unique)]
  id: String,
  #[multi_index(hashed_unique)]
  inner: Inner,
}
```

Except for the inner I'm not wanting 'it' to be hashed, rather I want the `inner.blah` to be hashed, what about being able to specify something like `#[multi_index(hashed_unique, extract = "&self.inner.blah")]` or so for an extraction expression (with the documentation of course that it should be fast and always return the same value).  Maybe better belong on the struct itself like `#[multi_index(indexes = {blah: "&self.inner.blah"})]` or something like that so it can have a more appropriate index name as well.

In addition, an index embedded in an Option, like say `inner: Option<Inner>` it would be nice to be an optional unique index, so it's a unique index if it exists, but if it doesn't exist then it's not part of that index at all.

**Comment by lun3x** [comment]
Hey, thanks I like the second idea! I've implemented the logic for this, and will make a release with this soon. Unfortunately I think the first idea adds too much complexity to this library, so I am closing this issue for now.

**Comment by Swoorup** [comment]
@lun3x  I am wondering has this been implemented? For my testing, it just treats the `Option<Inner>` as key instead of just `Inner`. 
Thinking we could add like ` #[multi_index(hashed_unique, optional)]` ?

> In addition, an index embedded in an Option, like say inner: Option<Inner> it would be nice to be an optional unique index, so it's a unique index if it exists, but if it doesn't exist then it's not part of that index at all.

Edit: Implemented in my fork [indexweave](https://github.com/Swoorup/indexweave/commit/177611846a3e7b84ae4b2a9550dde22bd17d8300)
